### ISSUE TITLE
Bump base dependency?

### ISSUE THREAD

**Issue by georgefst** [silkapp/generic-xmlpickler#1]
I've had no issues with `--allow-newer=generic-xmlpickler:base` on `ghc-8.6.5`, but it'd be nice to make it official.

**Comment by bergmark** [comment]
Needed to fiddle with the test suite as well, but looks fine
https://github.com/silkapp/generic-xmlpickler/pull/2

**Comment by bergmark** [comment]
Done! http://hackage.haskell.org/package/generic-xmlpickler-0.1.0.6

**Comment by georgefst** [comment]
Excellent. Great package by the way!

Now if only I could work out how to use `hxt`...
